#include "IDGenerator.h"
#include "FileManager.h"
#include "Logger.h"
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <system_error>

namespace fs = std::filesystem;


IDGenerator& IDGenerator::instance() {
    static IDGenerator inst;
    return inst;
}


IDGenerator::IDGenerator() {
    ensureCounterDirectory();
    load();
}


std::string IDGenerator::next(const std::string& prefix) {
    if (prefix.empty()) {
        Logger::instance().warn("IDGenerator::next called with empty prefix");
        return "";
    }

    int id = ++counters_[prefix];

    
    persist();

    return format(prefix, id);
}

std::string IDGenerator::peek(const std::string& prefix) const {
    if (prefix.empty()) return "";

    auto it = counters_.find(prefix);
    int next = (it != counters_.end()) ? it->second + 1 : 1;
    return format(prefix, next);
}

void IDGenerator::reload() {
    counters_.clear();
    load();
}


void IDGenerator::load() {
    std::ifstream file(FileManager::COUNTER_FILE);

    if (!file.is_open()) {
        
        Logger::instance().info("IDGenerator: no counter file found — starting all counters at 0");
        return;
    }

    std::string line;
    int lineNum = 0;

    while (std::getline(file, line)) {
        ++lineNum;
        if (line.empty() || line[0] == '#') continue;

        auto sep = line.find('=');
        if (sep == std::string::npos) {
            Logger::instance().warn(
                "IDGenerator: malformed line " + std::to_string(lineNum)
                + " in counter file — skipped"
            );
            continue;
        }

        std::string prefix = line.substr(0, sep);
        std::string valStr = line.substr(sep + 1);

        try {
            int val = std::stoi(valStr);
            if (val < 0) {
                Logger::instance().warn(
                    "IDGenerator: negative counter for prefix '" + prefix
                    + "' — resetting to 0"
                );
                val = 0;
            }
            counters_[prefix] = val;
        } catch (...) {
            Logger::instance().warn(
                "IDGenerator: invalid counter value '" + valStr
                + "' for prefix '" + prefix + "' — resetting to 0"
            );
            counters_[prefix] = 0;
        }
    }

    Logger::instance().info("IDGenerator: counters loaded from "
                            + std::string(FileManager::COUNTER_FILE));
}

void IDGenerator::persist() const {
    
    const std::string tmpPath = std::string(FileManager::COUNTER_FILE) + ".tmp";

    std::ofstream tmp(tmpPath, std::ios::trunc);
    if (!tmp.is_open()) {
        Logger::instance().error(
            "IDGenerator: could not write counter file: " + tmpPath
        );
        return;
    }

    tmp << "# Auto-generated by IDGenerator — do not edit manually\n";
    for (const auto& [prefix, count] : counters_) {
        tmp << prefix << '=' << count << '\n';
    }
    tmp.close();

    std::error_code ec;
    fs::rename(tmpPath, FileManager::COUNTER_FILE, ec);
    if (ec) {
        Logger::instance().error(
            std::string("IDGenerator: could not replace counter file: ")
            + ec.message()
        );
        
    }
}

std::string IDGenerator::format(const std::string& prefix, int counter) const {
    std::ostringstream oss;
    oss << prefix
        << std::setfill('0')
        << std::setw(padWidth(prefix))
        << counter;
    return oss.str();
}

int IDGenerator::padWidth(const std::string& prefix) noexcept {
    if (prefix == "BK" || prefix == "INV") return 6;
    return 3;   
}

void IDGenerator::ensureCounterDirectory() {
    std::error_code ec;
    fs::create_directories(FileManager::COUNTER_DIR, ec);
    if (ec) {
        Logger::instance().error(
            std::string("IDGenerator: could not create counter directory: ")
            + ec.message()
        );
    }
}
